INST_SERVER_PUB_NIC=ens3
INST_SERVER_PUB_IP=45.95.233.101
INST_SERVER_WG_NIC=awg0
INST_SERVER_WG_IPV4=10.9.8.1/24
INST_SERVER_WG_IPV6=fc00:66:66:66::1/64
INST_SERVER_PORT=60823
INST_SERVER_PRIV_KEY=8Nuq7BCXMdiejxkbUsfQSWO6sm/hbnZTHsi1594j+l4=
INST_SERVER_PUB_KEY=JLiio9V15PtQHfxfBApMCfGuGxDANfrRELclCkfD5Tk=
INST_CLIENT_DNS=192.168.15.3
INST_ALLOWED_IPS=0.0.0.0/0,::/0
