SSH_PORT=22
WG_PROTO=udp
WG_NET=10.9.8.0/24
WG_NET6=
PROVIDER_GW_MAC=08:05:e2:fa:07:f0
NFT_COUNTER=counter
NFT_NAT_NET="192.168.15.0/24, 192.168.16.0/24,192.168.25.0/24,192.168.26.0/24"
NFT_LIST_TRUSN_WAN='cl.vpn.mrovo.ru, cl-ang.vpn.mrovo.ru'
NFT_LIST_TRUST_VPN="192.168.15.0/24"
NFT_LIST_VPN=
NFT_LIST_VPN_ONLY=
NFT_LIST_INET_DROP=
# DNS сервер локальной сети
#NFT_DNS_LOCALNET=192.168.15.1
# DNS домены поиска для локальной сети
#NFT_SEARCH_DOMAIN_LOCALNET="domain1.qq domain2.df"
