SERVER_PUB_NIC=ens3
SERVER_PUB_IP=45.95.233.101
SERVER_WG_NIC=awg0
SERVER_WG_IPV4=10.9.8.1
SERVER_WG_IPV4_MASK=24
SERVER_WG_IPV6=
SERVER_WG_IPV6_MASK=
SERVER_PORT=60823
SERVER_PRIV_KEY=
SERVER_PUB_KEY=
CLIENT_DNS=192.168.15.3
ALLOWED_IPS=0.0.0.0/0,::/0
